# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TVShowCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVShowCase
  
  pod 'AlamofireImage', '~> 4.1'

  target 'TVShowCaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVShowCaseUITests' do
    # Pods for testing
  end

end
